### ISSUE TITLE
Keys starting with numbers don't seem to be persisted

### ISSUE THREAD

**Issue by dlasky** [allenluce/mmap-object#10]
```
const mmap = require('mmap-object');
var file = '/tmp/a';
var store = new mmap.Create(file);
store['12345'] = "test test test";
store.close();

var read = new mmap.Open(file);
console.log(read['12345']) //undefined;
```

Pretty trivial to work around on the JS side so maybe its worth just documenting it?

**Comment by allenluce** [comment]
I think it oughta work, and with https://github.com/allenluce/mmap-object/releases/tag/1.3.0 it should.  Please give it a shot and let me know if that does the trick.

**Comment by dlasky** [comment]
worked! Thank you!
