### ISSUE TITLE
Getting an error after uploading server to Amazon ECS.

### ISSUE THREAD

**Issue by cmhsu-cs** [allenluce/mmap-object#11]
It works locally but when I upload it, I'm seeing these errors in the logs: 

{ [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' } <==== (I'm not sure if this one is related to mmap-object)

Error: Error relocating /usr/src/app/node_modules/mmap-object/lib/mmap-object.node: __open64_2: symbol not found.

Thanks!

**Comment by allenluce** [comment]
Yeah, that first looks like a dotenv error. I don't think it's related.

The second looks to be a glib version mismatch. Can you look at the versions of glibc on the server vs. locally?

**Comment by allenluce** [comment]
Closing this for now, please reopen if it's still happening.
