### ISSUE TITLE
v1.4.2 not published to NPM

### ISSUE THREAD

**Issue by zbialecki** [allenluce/mmap-object#19]
Adding the line `"mmap-object": "^1.4.2"` to an app's package.json and running `npm install` results in the error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for mmap-object@^1.4.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

This is important as v1.4.1 is not compatible with Node v12.

**Comment by allenluce** [comment]
My omission! It's now published, please try again.

**Comment by zbialecki** [comment]
Thanks, it's working as expected now.
