### ISSUE TITLE
Some valid PropGet calls fail due to use of aho_corasick::trie

### ISSUE THREAD

**Issue by murpheywa** [allenluce/mmap-object#22]
In mmao-object.cc, the PropGetter function wants to ensure that the property name is not in the list of method names created by the buildMethods() function.

The problem is that `methodTrie.contains(string(*src))` returns true if the property name has a substring that matches one of the reserved method names.

For example, if I set a property named "xxxclosexxx", the set will succeed. However the PropGetter call will fail because "xxxclosexxx" contains the substring "close", and "close is stored in aho_corasick::trie methodTrie.

**Comment by allenluce** [comment]
Good catch!
