### ISSUE TITLE
is delete process-safe ?

### ISSUE THREAD

**Issue by bruceauyeung** [allenluce/mmap-object#28]
the case:
write shared memory in one proccess 
read and delete property in another process

is this safe ?

**Comment by allenluce** [comment]
@bruceauyeung It's not safe to do this with the version that's in `master`. There is a different version in the `writable` branch where it is safe. That branch has not had much testing but may be worth a try.

Note that the `writable` version uses a sharded key and will perform best where writes are much less frequent than reads and are spread among many keys. If you do decided to give it a spin, please let me know how it works for you.
