### ISSUE TITLE
Production safe?

### ISSUE THREAD

**Issue by brandonros** [allenluce/mmap-object#7]
I have some stuff that is too slow to pull out of Redis (50mb stringified + parsing is slow) that I need to share between processes. Is this the answer? Is this used in any production apps?

**Comment by brandonros** [comment]
Are you able to set JSON objects to keys as values or just strings?

**Comment by allenluce** [comment]
It's currently being used on several dozen RhythmMax Marketplace core servers which run around 70 Node processes per. On those it manages maybe 100 billion lookups a day.

It's fundamentally a key-value store. The keys are always strings (or the value of the `.toString()` method on whatever is used as a key). The values admit either strings or numbers (as an optimization).

Sharing objects among multiple processes takes a little doing. It can't really be done directly using native objects as object identity is per-process. The easiest way would be to serialize them into and out of shared memory. But then you can't really mix non-shared and shared objects effectively (the shared/non-shared boundary would always involve a copy).

In practice, users are handling the serialization/deserialization themselves:

```javascript
const myobject = {
    "some": "value"
}

shared_object["key"] = JSON.stringify(myobject)

// ...

const newobject = JSON.parse(shared_object["key"])

```

**Comment by allenluce** [comment]
@brandonros please let me know if this doesn't answer your question.

**Comment by brandonros** [comment]
> The keys are always strings (or the value of the .toString() method on whatever is used as a key).

I'd like to work with you on making that not the case. Do you think it is possible? How could we store objects in memroy that is accessible against multiple node.js threads/processes without having to stringify and parse them?

**Comment by allenluce** [comment]
Hey @brandonros, I'm sure it's possible given enough effort. I've been focusing on the read/write version of the package but am happy to review a pull request if you want to get things started.
