### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jcmoore** [allenluce/mmap-object#8]
I happened across this project looking for a mmap'ed kv-store to use to consume a lot of data from a kafka source and -- at least from some naive initial testing -- it looks like exactly what I'm looking for!

Unfortunately, it does seem though that this code is `UNLICENSED` which means that (generally speaking) it cannot be used in derivative works -- at least according to some naive initial research*.

I presume -- due to your [stackoverflow plug](http://stackoverflow.com/a/35283040) -- that it was not your intent to limit the use of this project/package.  Is that correct, and if so, can I "twist your arm" into adding a more explicitly-permissive license?

---
(*) Specifically this [stackexchange thread](http://softwareengineering.stackexchange.com/a/276147) and [gnu's license-list](http://www.gnu.org/licenses/license-list.html#NoLicense).

**Comment by allenluce** [comment]
Sure, check out the latest version.

**Comment by jcmoore** [comment]
Thanks very much!
